Translated quick start
reactjs/de.react.dev pull request #321
Opened 2023-04-27 14:30 UTC by tburakonat

Finished translating the Quick Start page 
#317

2023-04-29 23:49 UTC, ChrisB9 requested changes

2023-04-29 23:49 UTC, ChrisB9 commented on src/content/learn/index.md
> +Mit JSX kannst du deinem JavaScript Markup hinzufügen. Geschweifte Klammern lassen dich "zurück nach JavaScript" entkommen, so dass du eine Variable aus deinem Code einbetten und sie dem Benutzer anz
`dich "zurück nach JavaScript" entkommen`
entkommen klingt hier irgendwie sehr wortwörtlich übersetzt
Wie wäre es mit sowas: `lassen dich zu JavaScript "zurückkehren"` ?

2023-04-29 23:49 UTC, ChrisB9 commented on src/content/learn/index.md
> +Du kannst auch von JSX Attributen "nach JavaScript" entkommen, aber du musst geschweifte Klammern *anstatt von* Anführungszeichen verwenden. Zum Beispiel übergibt `className="avatar"` den String `"av
Selbiges dann hier

2023-04-29 23:49 UTC, ChrisB9 commented on src/content/learn/index.md
> +Um Listen von Komponenten zu rendern kannst du eine [`for` Schleife](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for) oder die [Array `map()` Funktion](https://develo
```suggestion
Um Listen von Komponenten zu rendern, kannst du eine [`for` Schleife](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for) oder die [Array `map()` Funktion](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map) verwenden.
```

2023-04-29 23:49 UTC, ChrisB9 commented on src/content/learn/index.md
> +Beachte, wie jedes `<li>` ein `key` Attribut hat. Für jedes Element in einer Liste solltest du einen String oder eine Zahl übergeben, die dieses Element eindeutig unter seinen Geschwister Elementen i
```suggestion
Beachte, wie jedes `<li>` ein `key` Attribut hat. Für jedes Element in einer Liste solltest du einen String oder eine Zahl übergeben, das dieses Element eindeutig unter seinen Geschwister Elementen identifiziert. Normalerweise sollte ein key aus deinen Daten stammen, wie z.B. eine Datenbank ID. React verwendet deine keys, um zu wissen, was passiert ist, wenn du später Elemente einfügst, löschst oder neu anordnest.
```

2023-04-29 23:49 UTC, ChrisB9 commented on src/content/learn/index.md
> +Zuerst importiere [`useState`](/reference/react/useState) von React:
darüber bin ich mir nicht sicher
```suggestion
Zuerst importiere [`useState`](/reference/react/useState) aus React:
```

2023-04-29 23:49 UTC, ChrisB9 commented on src/content/learn/index.md
> +Um beide `MyButton` Komponenten den selben `count` anzeigen zu lassen und zusammen zu aktualisieren, musst du den state von den einzelnen Buttons "nach oben" zur nächsten Komponente verschieben, die
```suggestion
Um beide `MyButton` Komponenten den selben `count` anzeigen zu lassen und zusammen zu aktualisieren, musst du den state von den einzelnen Buttons "nach oben" zur nächsten Komponente, die alle enthält, verschieben.
```

2023-04-29 23:49 UTC, ChrisB9 commented on src/content/learn/index.md
> +Zuerst *verschiebe den state* von `MyButton` *nach oben zu* `MyApp`:
```suggestion
Zuerst *verschiebe den state* von `MyButton` *nach oben* zu `MyApp`:
```

2023-04-29 23:49 UTC, ChrisB9 commented on src/content/learn/index.md
> +      <h1>Counters die sich zusammen ändern</h1>
```suggestion
      <h1>Counter, die sich zusammen ändern</h1>
```

2023-04-29 23:49 UTC, ChrisB9 commented on src/content/learn/index.md
> +      <h1>Counters die sich zusammen ändern</h1>
```suggestion
      <h1>Counter, die sich zusammen ändern</h1>
```

2023-04-29 23:49 UTC, ChrisB9 commented on src/content/learn/index.md
> +      <h1>Counter die sich zusammen ändern</h1>
```suggestion
      <h1>Counter, die sich zusammen ändern</h1>
```

2023-04-30 19:57 UTC, ThomasSpornraft commented on src/content/learn/index.md
> +Zuerst importiere [`useState`](/reference/react/useState) von React:
```suggestion
Als erstes musst du [`useState`](/reference/react/useState) aus React importieren
```

2023-04-30 19:57 UTC, ThomasSpornraft commented on src/content/learn/index.md
> +Zuerst importiere [`useState`](/reference/react/useState) von React:
ich tendiere zu "aus" weil man ja aus der React-Bibliothek importiert

2023-05-01 11:28 UTC, krsilas commented on src/content/learn/index.md
> +Beachte, dass `<MyButton />` mit einem Großbuchstaben beginnt. So weißt du, dass es sich um eine React Komponente handelt. React Komponentennamen müssen immer mit einem Großbuchstaben beginnen, währe
```suggestion
Beachte, dass `<MyButton />` mit einem Großbuchstaben beginnt. So weißt du, dass es sich um eine React Komponente handelt. React Komponentennamen müssen immer mit einem Großbuchstaben beginnen, während HTML-Tags kleingeschrieben werden müssen.
```

2023-05-04 07:32 UTC, ChrisB9 approved these changes

2023-05-05 07:42 UTC, merged