just translate the text
reactjs/de.react.dev pull request #323
Opened 2023-04-29 15:21 UTC by ThomasSpornraft

translated a few lines, no changes in functionality or design
I hope I followed the contribution guidelines

2023-04-29 22:57 UTC, ChrisB9 commented
It would have been helpful, if you would have read https://github.com/reactjs/de.react.dev/issues/317
I hope @gu-stav did not already start translating.
I'll put your name into the list already for installation

2023-07-23 15:20 UTC, ChrisB9 approved these changes

2023-07-23 15:22 UTC, ChrisB9 requested changes
I just saw that you also did do the editor-setup, can you please update or remove the file as someone else also did it

2023-07-23 16:19 UTC, closed without merging

2023-07-23 16:22 UTC, ThomasSpornraft commented
> 



> I just saw that you also did do the editor-setup, can you please update or remove the file as someone else also did it

Hi, i closed my pull reuqest hope this solves the problem.
Since I don't have time at the moment, I would ask you to remove me from the list of workers