Translate react developer tools
reactjs/de.react.dev pull request #348
Opened 2023-10-05 18:34 UTC by Dlurak

2023-11-21 10:33 UTC, ph1p requested changes

2023-11-21 10:33 UTC, ph1p commented on src/content/learn/react-developer-tools.md
> +Verbinde dann deine Webseite indem du das folgende `<script>` Tag zum Anfang des `<head>` deiner Webseite hinzufügst:
```suggestion
Verbinde dann deine Webseite, indem du das folgende `<script>` Tag zum Anfang des `<head>` deiner Webseite hinzufügst:
```

2023-11-21 10:33 UTC, ph1p commented on src/content/learn/react-developer-tools.md
> +Lade deine Webseite jetzt im Browser neu um die developer tools zu sehen.
```suggestion
Lade deine Webseite jetzt im Browser neu, um die Developer-Tools zu sehen.
```

2023-11-21 10:33 UTC, ph1p commented on src/content/learn/react-developer-tools.md
>  The easiest way to use React Developer Tools is to install it globally:
```suggestion
```

2023-11-21 10:33 UTC, ph1p commented on src/content/learn/react-developer-tools.md
> +Öffne als nächstes die developer tools aus dem Terminal:
```suggestion
Öffne als Nächstes die Developer Tools aus dem Terminal:
```

2023-11-21 10:33 UTC, ph1p commented on src/content/learn/react-developer-tools.md
> +> Versuche die App neuzuladen, falls die developer tools sich nicht nach einigen Sekunden verbinden.
```suggestion
> Versuche die App neu zuladen, falls die Developer-Tools sich nicht nach einigen Sekunden verbinden.
```

2023-11-21 10:34 UTC, ph1p commented
Thank you :) I added some suggestions

2023-11-21 13:54 UTC, Dlurak commented on src/content/learn/react-developer-tools.md
>  The easiest way to use React Developer Tools is to install it globally:
Oops, I've overlooked this line :sweat_smile:

2023-12-27 09:38 UTC, merged

2023-12-28 08:43 UTC, Dlurak commented
Wow, thanks for fixing all of these errors.